/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import util.Member;
import util.MemberDA;
import util.MemberTable;

/**
 *
 * @author Pete
 */
public class AddMember extends javax.swing.JPanel {

    /**
     * Creates new form Order
     */
    public AddMember() {
        initComponents();
        
    }
    
    public void UpdateRow() {
        int rowCount = tblMember.getRowCount();
        txtDesRowCount.setText(rowCount + "");
    }
    
    public void updateTable() {
        tblMember.setModel(new MemberTable().getModel(null));
    }
    
    public void updateSearch() {
        ArrayList<Object> data = new ArrayList<>();
        String sql = "";
        
        if(!txtID.getText().isBlank()) {
            sql += " AND customer_ID= ?";
            data.add(txtID.getText());
        }
        if(!txtFname.getText().isBlank()) {
            sql += " AND Cus_Fname= ?";
            data.add(txtFname.getText());
        }

        Object[] aData = new Object[]{sql,data};
        
        if(sql.isBlank()) {
            tblMember.setModel(new MemberTable().getModel(null));
        }else {
            tblMember.setModel(new MemberTable().getModel(aData));
        }
        
        UpdateRow();
    }
    
    public void addNewMember() {
        
        String fName = txtAddFname.getText();
        String lName = txtAddLname.getText();
        String cont = txtAddEmail.getText();
        
        Member aMember = new Member(0, fName, lName, cont);
        
        new MemberDA().addMember(aMember);
        
    }
    
    public void clearAdd() {
        txtAddFname.setText("");
        txtAddLname.setText("");
        txtAddEmail.setText("");
    }
    
    public boolean isAddFilled() {
        if(!(txtAddFname.getText().isBlank()&&txtAddLname.getText().isBlank()&&txtAddEmail.getText().isBlank())) {
            return true;
        }else {
            JOptionPane.showMessageDialog(AddPane, "form not filled.", "Warning", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddPane = new javax.swing.JPanel();
        btnAddClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        lbAddFname = new javax.swing.JLabel();
        txtAddFname = new javax.swing.JTextField();
        lbAdd = new javax.swing.JLabel();
        lbAddLname = new javax.swing.JLabel();
        txtAddLname = new javax.swing.JTextField();
        lbAddEmail = new javax.swing.JLabel();
        txtAddEmail = new javax.swing.JTextField();
        DescriptionPane = new javax.swing.JPanel();
        lbEditId = new javax.swing.JLabel();
        txtDesRowCount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        HeaderPane = new javax.swing.JPanel();
        lbPanalName = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lbFname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();

        setBackground(new java.awt.Color(239, 239, 239));

        AddPane.setBackground(new java.awt.Color(255, 255, 255));
        AddPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnAddClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddClear.setText("Clear");
        btnAddClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClearActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lbAddFname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbAddFname.setText("First Name :");

        txtAddFname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAddFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddFnameActionPerformed(evt);
            }
        });

        lbAdd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbAdd.setText("Add");

        lbAddLname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbAddLname.setText("Last Name : ");

        txtAddLname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAddLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddLnameActionPerformed(evt);
            }
        });

        lbAddEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbAddEmail.setText("Email :");

        txtAddEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAddEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPaneLayout = new javax.swing.GroupLayout(AddPane);
        AddPane.setLayout(AddPaneLayout);
        AddPaneLayout.setHorizontalGroup(
            AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPaneLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lbAdd)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(AddPaneLayout.createSequentialGroup()
                .addGroup(AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPaneLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddClear, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddPaneLayout.createSequentialGroup()
                                .addComponent(lbAddFname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAddFname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddPaneLayout.createSequentialGroup()
                                .addComponent(lbAddLname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAddLname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddPaneLayout.createSequentialGroup()
                                .addComponent(lbAddEmail)
                                .addGap(46, 46, 46)
                                .addComponent(txtAddEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AddPaneLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        AddPaneLayout.setVerticalGroup(
            AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbAdd)
                .addGap(50, 50, 50)
                .addGroup(AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAddFname))
                .addGap(18, 18, 18)
                .addGroup(AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAddLname))
                .addGap(18, 18, 18)
                .addGroup(AddPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAddEmail)
                    .addComponent(txtAddEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 448, Short.MAX_VALUE)
                .addComponent(btnAddClear)
                .addGap(18, 18, 18))
        );

        DescriptionPane.setBackground(new java.awt.Color(255, 255, 255));
        DescriptionPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lbEditId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbEditId.setText("Row : ");

        txtDesRowCount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDesRowCount.setEditable(false);

        javax.swing.GroupLayout DescriptionPaneLayout = new javax.swing.GroupLayout(DescriptionPane);
        DescriptionPane.setLayout(DescriptionPaneLayout);
        DescriptionPaneLayout.setHorizontalGroup(
            DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionPaneLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbEditId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDesRowCount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DescriptionPaneLayout.setVerticalGroup(
            DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DescriptionPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesRowCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEditId))
                .addContainerGap())
        );

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMember.setModel(new MemberTable().getModel(null));
        tblMember.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblMember.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblMember.getTableHeader().setReorderingAllowed(false);
        tblMember.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(tblMember);

        HeaderPane.setBackground(new java.awt.Color(255, 255, 255));

        lbPanalName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPanalName.setText("Member");

        lbID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbID.setText("ID : ");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setText("Serach");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lbFname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbFname.setText("First Name :");

        txtFname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderPaneLayout = new javax.swing.GroupLayout(HeaderPane);
        HeaderPane.setLayout(HeaderPaneLayout);
        HeaderPaneLayout.setHorizontalGroup(
            HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbFname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbPanalName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderPaneLayout.setVerticalGroup(
            HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPanalName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbFname)
                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch))
                    .addGroup(HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbID)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                    .addComponent(DescriptionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(HeaderPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        updateSearch();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtAddFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddFnameActionPerformed
        txtAddLname.requestFocus();
    }//GEN-LAST:event_txtAddFnameActionPerformed

    private void txtAddLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddLnameActionPerformed
        txtAddEmail.requestFocus();
    }//GEN-LAST:event_txtAddLnameActionPerformed

    private void txtAddEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddEmailActionPerformed
        btnAddActionPerformed(evt);
    }//GEN-LAST:event_txtAddEmailActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(isAddFilled()) {
            try {
                addNewMember();
                clearAdd();
                updateTable();

            }catch(Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAddClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClearActionPerformed
        clearAdd();
    }//GEN-LAST:event_btnAddClearActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        updateSearch();
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        updateSearch();
    }//GEN-LAST:event_txtFnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPane;
    private javax.swing.JPanel DescriptionPane;
    private javax.swing.JPanel HeaderPane;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAdd;
    private javax.swing.JLabel lbAddEmail;
    private javax.swing.JLabel lbAddFname;
    private javax.swing.JLabel lbAddLname;
    private javax.swing.JLabel lbEditId;
    private javax.swing.JLabel lbFname;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbPanalName;
    private javax.swing.JTable tblMember;
    private javax.swing.JTextField txtAddEmail;
    private javax.swing.JTextField txtAddFname;
    private javax.swing.JTextField txtAddLname;
    private javax.swing.JTextField txtDesRowCount;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
