/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JLayeredPane;

/**
 *
 * @author Pete
 */
public class Main extends javax.swing.JFrame {

//    Order order = new Order();
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
//        System.out.println(this.getWidth()+" : "+this.getHeight());
//        layeredPane.setSize(1374,887);
//        layeredPane.add(order, JLayeredPane.DEFAULT_LAYER);
//        order.setBounds(0,0,1328,869);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPane = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
        btnGame = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        layeredPane = new javax.swing.JLayeredPane();
        order1 = new main.Order();
        jMenuBar1 = new javax.swing.JMenuBar();
        mMenu = new javax.swing.JMenu();
        miOrder = new javax.swing.JMenuItem();
        miMember = new javax.swing.JMenuItem();
        miGame = new javax.swing.JMenuItem();
        miCategory = new javax.swing.JMenuItem();
        miStock = new javax.swing.JMenuItem();
        miEmp = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        imLogout = new javax.swing.JMenuItem();
        imExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1630, 919));

        buttonPane.setBackground(new java.awt.Color(255, 255, 255));
        buttonPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnOrder.setText("Order");
        btnOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        btnMember.setText("Membership");
        btnMember.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        btnGame.setText("Add Game");
        btnGame.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        btnCategory.setText("Add Categories");
        btnCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        btnUpdate.setText("Update stock");
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        btnEmployee.setText("Employee");
        btnEmployee.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        btnExit.setText("Exit");
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLogout.setText("Log out");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout buttonPaneLayout = new javax.swing.GroupLayout(buttonPane);
        buttonPane.setLayout(buttonPaneLayout);
        buttonPaneLayout.setHorizontalGroup(
            buttonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttonPaneLayout.setVerticalGroup(
            buttonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPaneLayout.createSequentialGroup()
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMember, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnGame, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 571, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layeredPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        layeredPane.setLayout(new java.awt.BorderLayout());
        layeredPane.add(order1, java.awt.BorderLayout.CENTER);

        mMenu.setText("Menu");

        miOrder.setText("Order");
        mMenu.add(miOrder);

        miMember.setText("Membership");
        mMenu.add(miMember);

        miGame.setText("Add Game");
        mMenu.add(miGame);

        miCategory.setText("Add Categories");
        mMenu.add(miCategory);

        miStock.setText("Update Stock");
        mMenu.add(miStock);

        miEmp.setText("Employee");
        mMenu.add(miEmp);
        mMenu.add(jSeparator1);

        imLogout.setText("Log out");
        mMenu.add(imLogout);

        imExit.setText("Exit");
        mMenu.add(imExit);

        jMenuBar1.add(mMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1374, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(layeredPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGame;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel buttonPane;
    private javax.swing.JMenuItem imExit;
    private javax.swing.JMenuItem imLogout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JMenu mMenu;
    private javax.swing.JMenuItem miCategory;
    private javax.swing.JMenuItem miEmp;
    private javax.swing.JMenuItem miGame;
    private javax.swing.JMenuItem miMember;
    private javax.swing.JMenuItem miOrder;
    private javax.swing.JMenuItem miStock;
    private main.Order order1;
    // End of variables declaration//GEN-END:variables
}
