/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;

/**
 *
 * @author Pete
 */
public class Main extends javax.swing.JFrame {

     Login parent;
     String rank;
    /**
     * Creates new form Main
     */
    public Main(Login frame, String rank) {
        this.parent = frame;
        this.rank = rank;
        initComponents(); 
        this.setSize(1646, 918);
        this.setLocationRelativeTo(null);
        isAdmin();
    }
    
    private void isAdmin() {
    if(!rank.equalsIgnoreCase("Admin")) {
            btnEmployee.setVisible(false);
            btnReport.setVisible(false);
            miEmp.setVisible(false);
            miReport.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPane = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
        btnGame = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        ccPane = new javax.swing.JPanel();
        OrderPane = new main.AddOrder();
        MemberPane = new main.AddMember();
        GamePane = new main.AddGame();
        EmployeePane = new main.AddEmployee();
        ReportPane = new main.ViewReport();
        aMenu = new javax.swing.JMenuBar();
        mMenu = new javax.swing.JMenu();
        miOrder = new javax.swing.JMenuItem();
        miMember = new javax.swing.JMenuItem();
        miGame = new javax.swing.JMenuItem();
        miCategory = new javax.swing.JMenuItem();
        miEmp = new javax.swing.JMenuItem();
        miReport = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miLogout = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1630, 919));
        setPreferredSize(new java.awt.Dimension(1630, 919));

        buttonPane.setBackground(new java.awt.Color(255, 255, 255));
        buttonPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnOrder.setText("Order");
        btnOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnMember.setText("Membership");
        btnMember.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });

        btnGame.setText("Add Game");
        btnGame.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGameActionPerformed(evt);
            }
        });

        btnEmployee.setText("Employee");
        btnEmployee.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLogout.setText("Log out");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnReport.setText("Report");
        btnReport.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPaneLayout = new javax.swing.GroupLayout(buttonPane);
        buttonPane.setLayout(buttonPaneLayout);
        buttonPaneLayout.setHorizontalGroup(
            buttonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMember, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
            .addComponent(btnGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttonPaneLayout.setVerticalGroup(
            buttonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPaneLayout.createSequentialGroup()
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMember, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnGame, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ccPane.setLayout(new java.awt.CardLayout());
        ccPane.add(OrderPane, "Order");
        ccPane.add(MemberPane, "Member");
        ccPane.add(GamePane, "Game");
        ccPane.add(EmployeePane, "Employee");
        ccPane.add(ReportPane, "Report");

        mMenu.setText("Menu");

        miOrder.setText("Order");
        miOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOrderActionPerformed(evt);
            }
        });
        mMenu.add(miOrder);

        miMember.setText("Membership");
        miMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMemberActionPerformed(evt);
            }
        });
        mMenu.add(miMember);

        miGame.setText("Add Game");
        miGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGameActionPerformed(evt);
            }
        });
        mMenu.add(miGame);

        miCategory.setText("Add Categories");
        mMenu.add(miCategory);

        miEmp.setText("Employee");
        miEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpActionPerformed(evt);
            }
        });
        mMenu.add(miEmp);

        miReport.setText("Report");
        miReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReportActionPerformed(evt);
            }
        });
        mMenu.add(miReport);
        mMenu.add(jSeparator1);

        miLogout.setText("Log out");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mMenu.add(miLogout);

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mMenu.add(miExit);

        aMenu.add(mMenu);

        setJMenuBar(aMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ccPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        CardLayout card = (CardLayout)ccPane.getLayout();
        card.show(ccPane, "Order");
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        CardLayout card = (CardLayout)ccPane.getLayout();
        card.show(ccPane, "Member");
    }//GEN-LAST:event_btnMemberActionPerformed

    private void btnGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGameActionPerformed
CardLayout card = (CardLayout)ccPane.getLayout();
        card.show(ccPane, "Game");
    }//GEN-LAST:event_btnGameActionPerformed

    private void miOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOrderActionPerformed
        btnOrder.doClick();
    }//GEN-LAST:event_miOrderActionPerformed

    private void miMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMemberActionPerformed
        btnMember.doClick();
    }//GEN-LAST:event_miMemberActionPerformed

    private void miGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGameActionPerformed
        btnGame.doClick();
    }//GEN-LAST:event_miGameActionPerformed

    private void miEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmpActionPerformed
        btnEmployee.doClick();
    }//GEN-LAST:event_miEmpActionPerformed

    private void miReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReportActionPerformed
        btnReport.doClick();
    }//GEN-LAST:event_miReportActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        btnLogout.doClick();
    }//GEN-LAST:event_miLogoutActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
CardLayout card = (CardLayout)ccPane.getLayout();
        card.show(ccPane, "Employee");
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
CardLayout card = (CardLayout)ccPane.getLayout();
        card.show(ccPane, "Report");
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        btnExit.doClick();
    }//GEN-LAST:event_miExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main(new Login(), "Admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.AddEmployee EmployeePane;
    private main.AddGame GamePane;
    private main.AddMember MemberPane;
    private main.AddOrder OrderPane;
    private main.ViewReport ReportPane;
    private javax.swing.JMenuBar aMenu;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGame;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnReport;
    private javax.swing.JPanel buttonPane;
    private javax.swing.JPanel ccPane;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mMenu;
    private javax.swing.JMenuItem miCategory;
    private javax.swing.JMenuItem miEmp;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miGame;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miMember;
    private javax.swing.JMenuItem miOrder;
    private javax.swing.JMenuItem miReport;
    // End of variables declaration//GEN-END:variables
}
