/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

/**
 *
 * @author Pete
 */
public class Order extends javax.swing.JPanel {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CartPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        lbCartQuantity = new javax.swing.JLabel();
        txtCartQuantity = new javax.swing.JTextField();
        btnCartPlus = new javax.swing.JButton();
        btnCartMinus = new javax.swing.JButton();
        btnCartAdd = new javax.swing.JButton();
        btnCartRemove = new javax.swing.JButton();
        lbCartMember = new javax.swing.JLabel();
        txtCartMember = new javax.swing.JTextField();
        btnCartMember = new javax.swing.JButton();
        btnCartPrint = new javax.swing.JButton();
        btnCartProcess = new javax.swing.JButton();
        btnCartClear = new javax.swing.JButton();
        DescriptionPane = new javax.swing.JPanel();
        lbDesName = new javax.swing.JLabel();
        txtDesName = new javax.swing.JTextField();
        lbDesDescription = new javax.swing.JLabel();
        lbDesQuantity = new javax.swing.JLabel();
        txtDesQuantity = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtADescription = new javax.swing.JTextArea();
        lbDesStatus = new javax.swing.JLabel();
        txtDesStatus = new javax.swing.JTextField();
        lbDesPrice = new javax.swing.JLabel();
        txtDesPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        HeaderPane = new javax.swing.JPanel();
        lbPanalName = new javax.swing.JLabel();
        lbSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbCategory = new javax.swing.JComboBox<>();
        lbCategory = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 239, 239));

        CartPane.setBackground(new java.awt.Color(255, 255, 255));
        CartPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblCart.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCart.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCart.getTableHeader().setReorderingAllowed(false);
        tblCart.setAutoCreateRowSorter(true);
        jScrollPane3.setViewportView(tblCart);

        lbCartQuantity.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbCartQuantity.setText("Quantity :");

        txtCartQuantity.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDesQuantity.setEditable(false);

        btnCartPlus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCartPlus.setText("+");

        btnCartMinus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCartMinus.setText("-");

        btnCartAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCartAdd.setText("Add");

        btnCartRemove.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCartRemove.setText("Remove");

        lbCartMember.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbCartMember.setText("Membership :");

        txtCartMember.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDesQuantity.setEditable(false);

        btnCartMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCartMember.setText("placeHolder");

        btnCartPrint.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCartPrint.setText("Print Receipt");

        btnCartProcess.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCartProcess.setText("Proccess");

        btnCartClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCartClear.setText("Clear");

        javax.swing.GroupLayout CartPaneLayout = new javax.swing.GroupLayout(CartPane);
        CartPane.setLayout(CartPaneLayout);
        CartPaneLayout.setHorizontalGroup(
            CartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(CartPaneLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(CartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CartPaneLayout.createSequentialGroup()
                        .addComponent(lbCartMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCartMember))
                    .addGroup(CartPaneLayout.createSequentialGroup()
                        .addComponent(btnCartAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCartRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CartPaneLayout.createSequentialGroup()
                        .addComponent(lbCartQuantity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCartPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCartMinus))
                    .addGroup(CartPaneLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(CartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCartPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCartMember, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCartProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCartClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        CartPaneLayout.setVerticalGroup(
            CartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartPaneLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(CartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCartQuantity)
                    .addComponent(txtCartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCartPlus)
                    .addComponent(btnCartMinus))
                .addGap(18, 18, 18)
                .addGroup(CartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCartAdd)
                    .addComponent(btnCartRemove))
                .addGap(18, 18, 18)
                .addGroup(CartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCartMember)
                    .addComponent(txtCartMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCartMember)
                .addGap(33, 33, 33)
                .addComponent(btnCartProcess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCartPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(btnCartClear)
                .addGap(18, 18, 18))
        );

        DescriptionPane.setBackground(new java.awt.Color(255, 255, 255));
        DescriptionPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lbDesName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbDesName.setText("Name :");

        txtDesName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDesName.setEditable(false);

        lbDesDescription.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbDesDescription.setText("Description :");

        lbDesQuantity.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbDesQuantity.setText("Quantity :");

        txtDesQuantity.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDesQuantity.setEditable(false);

        txtADescription.setColumns(20);
        txtADescription.setRows(5);
        txtADescription.setEditable(false);
        jScrollPane2.setViewportView(txtADescription);

        lbDesStatus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbDesStatus.setText("Status :");

        txtDesStatus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDesStatus.setEditable(false);

        lbDesPrice.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbDesPrice.setText("Price :");

        txtDesPrice.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDesPrice.setEditable(false);

        javax.swing.GroupLayout DescriptionPaneLayout = new javax.swing.GroupLayout(DescriptionPane);
        DescriptionPane.setLayout(DescriptionPaneLayout);
        DescriptionPaneLayout.setHorizontalGroup(
            DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionPaneLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDesDescription)
                    .addComponent(lbDesName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(txtDesName))
                .addGap(18, 18, 18)
                .addGroup(DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDesQuantity)
                    .addComponent(lbDesPrice)
                    .addComponent(lbDesStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDesStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        DescriptionPaneLayout.setVerticalGroup(
            DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionPaneLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DescriptionPaneLayout.createSequentialGroup()
                        .addGroup(DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDesStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDesStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDesQuantity)
                            .addComponent(txtDesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDesPrice)
                            .addComponent(txtDesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DescriptionPaneLayout.createSequentialGroup()
                        .addGroup(DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDesName)
                            .addComponent(txtDesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDesDescription)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStock.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblStock.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblStock.getTableHeader().setReorderingAllowed(false);
        tblStock.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(tblStock);

        HeaderPane.setBackground(new java.awt.Color(255, 255, 255));

        lbPanalName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPanalName.setText("Order");

        lbSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSearch.setText("Search :");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setText("id");

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setText("Serach");

        cbCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbCategory.setText("Category :");

        javax.swing.GroupLayout HeaderPaneLayout = new javax.swing.GroupLayout(HeaderPane);
        HeaderPane.setLayout(HeaderPaneLayout);
        HeaderPaneLayout.setHorizontalGroup(
            HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPaneLayout.createSequentialGroup()
                .addGroup(HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderPaneLayout.createSequentialGroup()
                        .addGap(592, 592, 592)
                        .addComponent(lbPanalName))
                    .addGroup(HeaderPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderPaneLayout.setVerticalGroup(
            HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPanalName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCategory))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(DescriptionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CartPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(HeaderPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CartPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CartPane;
    private javax.swing.JPanel DescriptionPane;
    private javax.swing.JPanel HeaderPane;
    private javax.swing.JButton btnCartAdd;
    private javax.swing.JButton btnCartClear;
    private javax.swing.JButton btnCartMember;
    private javax.swing.JButton btnCartMinus;
    private javax.swing.JButton btnCartPlus;
    private javax.swing.JButton btnCartPrint;
    private javax.swing.JButton btnCartProcess;
    private javax.swing.JButton btnCartRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbCartMember;
    private javax.swing.JLabel lbCartQuantity;
    private javax.swing.JLabel lbCategory;
    private javax.swing.JLabel lbDesDescription;
    private javax.swing.JLabel lbDesName;
    private javax.swing.JLabel lbDesPrice;
    private javax.swing.JLabel lbDesQuantity;
    private javax.swing.JLabel lbDesStatus;
    private javax.swing.JLabel lbPanalName;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblStock;
    private javax.swing.JTextArea txtADescription;
    private javax.swing.JTextField txtCartMember;
    private javax.swing.JTextField txtCartQuantity;
    private javax.swing.JTextField txtDesName;
    private javax.swing.JTextField txtDesPrice;
    private javax.swing.JTextField txtDesQuantity;
    private javax.swing.JTextField txtDesStatus;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
