/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import com.formdev.flatlaf.FlatLightLaf;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import util.*;

/**
 *
 * @author SP_ONE
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icon/g.png")).getImage());
    }
    
    public PrintReceipt(Bill aBill) {
        initComponents();
//        jTextArea1.setEnabled(false);
        clear();
        setString(aBill);
        setVisible(true);
    }
    
    public PrintReceipt(Bill aBill, boolean a) {
        initComponents();
        clear();
        setPast(aBill);
        setVisible(true);
    }
    
    public void setString(Bill aBill) {
        String str ="\n"+
                "\t   ---Game Shop---\n";
                
        str +=  "\t "+ java.sql.Timestamp.valueOf(LocalDateTime.now().withNano(0))+"\n"+
                "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\n\n"+
                "\t     CASH RECEIPT\n\n"+
                "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\n"+
                "Description\t\t\tPrice\n";
        
        for(int i = 0; i< aBill.getGame().size(); i++) {
            str += "\n"+aBill.getGame().get(i).getName() +"\n" ;
            str +=  aBill.getAmount().get(i) + "\t\t\t" +aBill.getGame().get(i).getPrice();
        }             
         str += "\n"+
                "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\n\n";
         str += "Total\t\t\t"+aBill.getTotal() +"\n"+
                "\t\t\t"+ aBill.getMember().getId()+"\n"+
                "discount\t\t\t"+ aBill.getDiscount()+"\n\n"+
                "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\n\n"+
                "\t ----Thank you----";
                
        jTextArea1.setText(str);
    }
    
    public void setPast(Bill aBill) {
        String str ="\n"+
                "\t   ---Game Shop---\n";
                
        str +=  "\t "+ aBill.getDate()+"\n"+
                "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\n\n"+
                "\t     CASH RECEIPT\n\n"+
                "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\n"+
                "Description\t\t\tPrice\n";
        
        for(int i = 0; i< aBill.getGame().size(); i++) {
            str += "\n"+aBill.getGame().get(i).getName() +"\n" ;
            str +=  aBill.getAmount().get(i) + "\t\t\t" +aBill.getGame().get(i).getPrice();
        }             
         str += "\n"+
                "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\n\n";
         str += "Total\t\t\t"+aBill.getTotal() +"\n"+
                "\t\t\t"+ aBill.getMember().getId()+"\n"+
                "discount\t\t\t"+ aBill.getDiscount()+"\n\n"+
                "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\n\n"+
                "\t ----Thank you----";
                
        jTextArea1.setText(str);
    }
    
    public void clear() {
        jTextArea1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(247, 247, 247));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\t   ---Game Shop---\n\t 00,00,00-00:00:0000\n* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\n\n\t     CASH RECEIPT\n\n* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\nDescription\t\t\tPrice\n\nasdsadadasdasdasdasdasdas\t\t0000\ndadadadasdasdasd\t\t0000\nasdadadasdadas\t\t0000\n\n* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\n\nTotal\t\t\t0000\n\t\t\t0000\ndiscount\t\t\t0000\n\n* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\n\n\t ----Thank you----\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
